makeIndex <- function()
  {
    filename <- paste(nfl.par@website.location,"/index.html",sep="")
    sink(filename)
    cat("<p>\n",
        "Predictions are available for the 2011 NFL season, as well as parameter estimates for each team's points scored and allowed, adjusting for opponent. The predictions are generated by a Bayesian model that assumes a Gaussian distribution for the two scores in a football game.\n",
        "</p>\n",
        "<p>\n",
        "Predictions are given for all weeks of the season based on the available data at that time. The most recent predictions for a given week are kept posted so that they may be looked back on and judged. For example, the predictions for Week 6 keep changing every week until we obtain Week 5 data, after which it remains as the prediction for Week 6 given data from Weeks 1-5 (and prior seasons).\n",
        "</p>\n",
        "<p>\n",
        "Updated: ",as.character(Sys.time()),"\n",
        "</p>\n",
        sep="")
    sink()
  }
